### ISSUE TITLE
Logo Design For Standup Alarm

### ISSUE THREAD

**Issue by zularizal** [casey-mcbride/Standup-Alarm#1]
Hi @casey-mcbride , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. Don't worry about fees, it's free for you. What do you think?

**Comment by casey-mcbride** [comment]
Sorry, I just noticed this comment (fairly new to Github). You do good work, but since this project is probably only really used by me right now, and is still buggy, I don't know if it's worth your time. I'm mostly just using it to learn Android and Git.

Thanks for the offer.
